### PR TITLE
Added CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by dbrgn**
What do you think about this, @rnestler @schmijos @dns2utf8?

We could also use it for other projects.

### CODE REVIEW

**Comment by rnestler** [comment]
Didn't we have something similar in 286889ad01394c155e4c16f265f8222936454b63 ?

**Comment by dbrgn** [comment]
Hm, true :/ Was probably lost in the switch from Python to Rust.

Anyways, what do you think about the current version? And should we re-introduce `AUTHORS.md`?

**Comment by dns2utf8** [comment]
I already did XP

I like the new version better.

**Comment by dbrgn** [comment]
Alright!

**Pull request merged**
