### PR TITLE
Removed spaceapi sub-crate

### PR DESCRIPTION
**Pull request by dbrgn**
It has moved to https://github.com/coredump-ch/spaceapi-rs.

Can someone review this?

### CODE REVIEW

**Comment by dbrgn** [comment]
Refs #70.

**Comment by rnestler** [comment]
Awesome! Looks good to me :smiley: And still compiles, runs and passes CI

**Comment by rnestler** [comment]
Sorry I just had to rebase and correct the commit message :wink:

**Comment by dbrgn** [comment]
Ahaha. Old habits die hard.

**Pull request merged**
