### PR TITLE
Upgrade rust version in Dockerfile

### PR DESCRIPTION
**Pull request by dbrgn**
We need this for the deployment.

### CODE REVIEW

**Comment by dns2utf8** [comment]
I would like to clean the compile env. Testing now.

**Comment by dbrgn** [comment]
Cool, thx!

Small git commit message nazi comment, to make @rnestler happy: Can you write the messages without punctuation and in imperative form (`Remove build directory...`)?

http://chris.beams.io/posts/git-commit/

**Comment by rnestler** [comment]
Yes every commit message not compliant with http://chris.beams.io/posts/git-commit/#imperative will be rewritten :wink:

**Comment by dbrgn** [comment]
@dns2utf8 also we have a review policy for all team repos, so you shouldn't merge any pull request without review by another person. :)

**Pull request merged**
