### PR TITLE
Dockerfile

### PR DESCRIPTION
**Pull request by dbrgn**
This is based on PR #36, so please merge that one first.

This commit introduces a Dockerfile for easier deployment.

@schmijos @rnestler please review :)

### CODE REVIEW

**Comment by rnestler** [comment]
This one needs some rebasing since #36 got merged

**Comment by dbrgn** [comment]
Done.

**Comment by dbrgn** [comment]
Ping? :)

**Comment by rnestler** [comment]
I have no experience with docker, so I trust you on this one :wink:

**Pull request merged**
