### PR TITLE
Redis Datastore

### PR DESCRIPTION
**Pull request by dbrgn**
I created a generic datastore interface to store strings. We could later expand it with other data types.

Then I added a Redis implementation for that datastore and started using it from `main.rs`.

There are also some basic tests in `redis_store.rs`, you can run them with `cargo test` (you need a running Redis instance though).

@rnestler can you take a look at the current changes? :)

### CODE REVIEW

**Comment by dbrgn** [comment]
Ach Mist, die Testsuite läuft noch nicht auf Travis weil Redis da noch fehlt.

**Comment by rnestler** [comment]
huiuiui

**Comment by dbrgn** [comment]
By the way, can we somehow differentiate between "this field is `null`" and "this field should not be included at all in the response JSON"?

**Comment by dbrgn** [comment]
Yaaay, "all is well"! :)

Travia hat nun auch IRC-Integration auf #coredump.

**Comment by dbrgn** [comment]
I added some more improvements.

@rnestler, we somehow need to find a way to not include objects like `people_present` at all if they don't contain anything, instead of including them as an empty array. Do you have any idea besides implementing `ToJson`?

**Comment by rnestler** [comment]
This pull request is getting a little out of control... It actually includes now the complete rust branch (bd42eee0dd4ee3edca14bc2fe2df8c0d4ef624db) as well. How do you want to proceed? Delete the rust branch and merge this branch to master?

**Comment by rnestler** [comment]
Also, do we intend to remove the python implementation once the rust version is ready?

**Comment by dbrgn** [comment]
> This pull request is getting a little out of control...

True, let's just merge it to the rust branch, which is still in initial dev anyways :) I got sidetracked.

> It actually includes now the complete rust branch (bd42eee) as well. 

That's because this pull request is actually created against the rust branch, not against master :)

> Also, do we intend to remove the python implementation once the rust version is ready?

Yes.

> How do you want to proceed?

I'll merge this into the `rust` branch. Then we can continue working there and create pull requests against `rust` until it's ready to be deployed. Is that fine for you? :)

**Comment by rnestler** [comment]
@dbrgn, does the Space API allow null for not existing objects? In that case we can just use ``Option<T>`` because the default serialization converts ``None`` to ``null``.

For example ``optional: None`` -> ``"optional":null``

**Comment by dbrgn** [comment]
I already did that for some of the fields. I'll open a new issue.

**Comment by rnestler** [comment]
> That's because this pull request is actually created against the rust branch, not against master :)

Now it is, but some minutes ago it was based on 07bb169f8da95d224378db6f9cdc6be530ad6b90 which confused me

> I'll merge this into the rust branch. Then we can continue working there and create pull requests against rust until it's ready to be deployed. Is that fine for you? :)

Since you rebased so nicely you could just fast forward into the rust branch. That way we have less merge noise in the history

**Comment by dbrgn** [comment]
> Now it is, but some minutes ago it was based on 07bb169 which confused me

In that case something went wrong, sorry. It's possible that I rebased locally, where my redis branch wasn't up to date yet.

> Since you rebased so nicely you could just fast forward into the rust branch. That way we have less merge noise in the history

Would have been a good idea. Too late now, sorry. I could try to squash the merge commit, but that usually goes wrong :)

Let's discuss our development workflow at the next meeting.

**Pull request merged**
